//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amkor_Material_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int DefaultSaftyTime {
            get {
                return ((int)(this["DefaultSaftyTime"]));
            }
            set {
                this["DefaultSaftyTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyncOutExcel {
            get {
                return ((bool)(this["SyncOutExcel"]));
            }
            set {
                this["SyncOutExcel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SyncOUtExcelPath {
            get {
                return ((string)(this["SyncOUtExcelPath"]));
            }
            set {
                this["SyncOUtExcelPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LongTimeReelReportMonth {
            get {
                return ((int)(this["LongTimeReelReportMonth"]));
            }
            set {
                this["LongTimeReelReportMonth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true,byeongun.choi@amkor.co.kr;")]
        public string LongTimeReelReportMail {
            get {
                return ((string)(this["LongTimeReelReportMail"]));
            }
            set {
                this["LongTimeReelReportMail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LongTimeReelReportInterval1 {
            get {
                return ((int)(this["LongTimeReelReportInterval1"]));
            }
            set {
                this["LongTimeReelReportInterval1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int LongTimeReelReportInterval2 {
            get {
                return ((int)(this["LongTimeReelReportInterval2"]));
            }
            set {
                this["LongTimeReelReportInterval2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("안녕하세요.")]
        public string LongTimeReelReporthead {
            get {
                return ((string)(this["LongTimeReelReporthead"]));
            }
            set {
                this["LongTimeReelReporthead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("감사합니다.")]
        public string LongTimeReelReportTail {
            get {
                return ((string)(this["LongTimeReelReportTail"]));
            }
            set {
                this["LongTimeReelReportTail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LongTermReelReportPath {
            get {
                return ((string)(this["LongTermReelReportPath"]));
            }
            set {
                this["LongTermReelReportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int LongTimeReelReportHour {
            get {
                return ((int)(this["LongTimeReelReportHour"]));
            }
            set {
                this["LongTimeReelReportHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WWnn 주 장기보관 Reel Report 입니다.")]
        public string LongTimeReelReportSubject {
            get {
                return ((string)(this["LongTimeReelReportSubject"]));
            }
            set {
                this["LongTimeReelReportSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LongTermReelReportEN {
            get {
                return ((bool)(this["LongTermReelReportEN"]));
            }
            set {
                this["LongTermReelReportEN"] = value;
            }
        }
    }
}
